### ISSUE TITLE
Able to open two config windows at once

### ISSUE THREAD

**Issue by staadecker** [rongrimes/conway#1]
I am able to open two config windows at once. It would be more accurate if pressing config when the window is already open raises the config window.

**Comment by rongrimes** [comment]
Thanks @SUPERETDUPER (Martin), and you're right! (Urg!)  
I'll fix this... real soon now (next few days I hope).

**Comment by rongrimes** [comment]
Hi @SUPERETDUPER (Martin):
Fixed... at long last. Thanks for the issue note.
